import type { ContentItem } from './content-types';

const common = {
  platforms: ['Instagram'], owner: 'Aitor' as const, priority: 'media' as const,
  script: '', fileLinks: [] as string[], driveLink: '', notes: '', publishedAt: '', metrics: '',
};

const item = (value: Partial<ContentItem> & Pick<ContentItem, 'id' | 'title' | 'scheduledAt' | 'format' | 'campaign' | 'status'>): ContentItem => ({
  ...common,
  objective: 'Build trust and appetite through real craft.',
  hook: '', idea: '', copy: '', cta: 'Visit us in Biddeford.', shotList: '', instructions: '',
  ...value,
});

export const SEPTEMBER_CONTENT: ContentItem[] = [
  item({ id: 'giveaway-5000', title: '5K community giveaway', scheduledAt: '2026-09-01T09:00:00-04:00', format: 'Carrusel', campaign: '5,000 Followers Giveaway', status: 'publicado', priority: 'alta', owner: 'compartido', objective: 'Celebrate 5,000 followers and reward the local community.', hook: '5,000 of you. One very sweet thank-you.', idea: 'Published giveaway launch; monitor entries and prepare winner follow-up.', copy: 'Biddeford, we are 5,000 strong. To celebrate, we are sharing a little piece of Edelweiss with one of you. Thank you for making room for our tiny bakery in your days.', cta: 'Enter on the original giveaway post.', shotList: 'Published carousel and Reel assets.', instructions: 'No new filming required. Reply to genuine comments in short batches.', fileLinks: ['C:\\STUDIOS-MEDIA\\social\\clientes\\edelweiss\\deliverables\\2026-08-28-giveaway-5000'], publishedAt: '2026-09-01T09:00:00-04:00', metrics: 'Complete after giveaway closes.' }),
  item({ id: 'croissant-reel', title: 'The three-day croissant process', scheduledAt: '2026-09-03T10:00:00-04:00', format: 'Reel', campaign: 'Three Days Inside a Croissant', status: 'pendiente de grabación', priority: 'alta', hook: 'This croissant started three days ago.', idea: 'A tactile, quiet Reel moving from dough to golden layers.', script: 'Day one: dough. Day two: butter and folds. Day three: proof, bake, and the first crackle.', copy: 'Three days, a lot of butter, and no shortcuts. Every layer has somewhere to be.', cta: 'Save this for your next Biddeford morning.', shotList: 'Hands mixing; butter block; lamination; cut triangles; roll; proof; oven; split croissant.', instructions: 'Alex: phone on tripod, vertical, 2–3 seconds per step. No talking and no face needed.', need: { request: 'Croissant process: hands, folds, oven and final break.', how: '8–10 steady clips; phone fixed or slow close-up.', duration: '12 min across the process', orientation: 'Vertical 9:16', deadline: '2026-09-02', reference: 'Warm, close, texture-first.', delivered: false } }),
  item({ id: 'croissant-story-1', title: 'Croissant texture + poll', scheduledAt: '2026-09-05T08:30:00-04:00', format: 'Story', campaign: 'Three Days Inside a Croissant', status: 'idea', hook: 'Would you wait three days for this crunch?', idea: 'Reuse final break shot with a simple poll.', copy: 'Worth the wait?', cta: 'Poll: Absolutely / Save me one', shotList: 'Reuse croissant Reel close-up.', instructions: 'No additional filming.' }),
  item({ id: 'community-post', title: 'Five thousand thank-yous', scheduledAt: '2026-09-08T10:00:00-04:00', format: 'Post', campaign: '5,000 Followers Giveaway', status: 'idea', hook: 'A small bakery, a very big thank-you.', idea: 'Community gratitude post after the giveaway closes.', copy: 'Five thousand people found our little Swiss bakery in Maine. We still feel every hello at the counter. Thank you for being here.', cta: 'Tell us what first brought you through our door.', shotList: 'Exterior, counter detail, hands passing pastry.', instructions: 'Use archive material; no founder appearance required.' }),
  item({ id: 'three-days-carousel', title: 'What three days inside a croissant really means', scheduledAt: '2026-09-10T10:00:00-04:00', format: 'Carrusel', campaign: 'Three Days Inside a Croissant', status: 'idea', priority: 'alta', hook: 'What three days inside a croissant really means', idea: 'Editorial 6-slide explanation with restrained typography and macro texture.', copy: 'A croissant does not need rushing. It needs cold butter, patient folds, a long rest, and one very hot oven.', cta: 'Swipe through the process. Then come hear the crunch.', shotList: 'Reuse process frames from Reel.', instructions: 'No additional filming.' }),
  item({ id: 'process-story', title: 'Fold by fold', scheduledAt: '2026-09-12T08:30:00-04:00', format: 'Story', campaign: 'Three Days Inside a Croissant', status: 'idea', hook: 'Fold by fold.', idea: 'Three frames: butter, fold, layers.', copy: 'Patience you can taste.', cta: 'Question sticker: What should we show next?', shotList: 'Reuse lamination clips.', instructions: 'No additional filming.' }),
  item({ id: 'swiss-heritage', title: 'A little Switzerland in Maine', scheduledAt: '2026-09-15T10:00:00-04:00', format: 'Post', campaign: 'Swiss Heritage', status: 'pendiente de grabación', hook: 'Swiss roots. Maine mornings.', idea: 'Still life joining a Swiss pastry, linen, wood and the Biddeford shop.', copy: 'Our recipes carry Switzerland with them. Our days belong to Biddeford. Edelweiss lives somewhere warm between the two.', cta: 'Come find your favorite piece of Switzerland.', shotList: 'Pastry still life; shop window; packaging detail.', instructions: 'Valentina: 4 photos by the window, no people needed.', need: { request: 'One Swiss pastry still life and one shop-window photo.', how: 'Natural window light, clean background, close and wide versions.', duration: '8 min', orientation: 'Vertical + square', deadline: '2026-09-14', reference: 'Warm editorial still life, not glossy.', delivered: false } }),
  item({ id: 'autumn-tease-story', title: 'Autumn is entering the bakery', scheduledAt: '2026-09-17T16:00:00-04:00', format: 'Story', campaign: 'Autumn at Edelweiss', status: 'idea', hook: 'Something warmer is coming.', idea: 'Ingredient macro tease without revealing the full product.', copy: 'Autumn is entering the bakery.', cta: 'Guess the flavor.', shotList: 'Spice, chocolate, fruit or dough macro.', instructions: 'Capture during the same biweekly session.' }),
  item({ id: 'autumn-products', title: 'First tastes of autumn', scheduledAt: '2026-09-19T09:00:00-04:00', format: 'Carrusel', campaign: 'Autumn at Edelweiss', status: 'pendiente de grabación', priority: 'alta', hook: 'The bakery changes with the light.', idea: 'Seasonal product carousel with jewel-like chocolate details.', copy: 'Crisper mornings call for deeper chocolate, warmer spice, and pastry fresh from the oven.', cta: 'Which one should stay all season?', shotList: '3 seasonal products; chocolate macro; full counter grouping.', instructions: 'Alex + Valentina: place products, Aitor handles shooting.', need: { request: 'Set aside 3 autumn products and one chocolate detail.', how: 'Aitor photographs; only help arrange the products.', duration: '10 min', orientation: 'Square + vertical', deadline: '2026-09-18', reference: 'Chocolate photographed like jewelry.', delivered: false } }),
  item({ id: 'bts-story', title: 'Before Biddeford wakes up', scheduledAt: '2026-09-22T07:00:00-04:00', format: 'Story', campaign: 'Behind the Scenes', status: 'idea', hook: 'Before the day gets loud.', idea: 'Quiet early-morning bakery sequence.', copy: 'The ovens are already awake.', cta: 'Tap through the morning.', shotList: 'Lights on; oven; trays; first pastry.', instructions: 'Tripod clips, no faces or dialogue.' }),
  item({ id: 'wholesale-post', title: 'Made for your counter, too', scheduledAt: '2026-09-24T10:00:00-04:00', format: 'Post', campaign: 'Wholesale', status: 'idea', hook: 'Your customers can wake up with Edelweiss, too.', idea: 'Wholesale introduction for local cafés and hospitality partners.', copy: 'Three-day croissants and Swiss pastry, made in Biddeford for thoughtful counters across Southern Maine.', cta: 'Ask us about wholesale availability.', shotList: 'Tray rows, packing, boxes ready to leave.', instructions: 'Use production footage from the biweekly session.' }),
  item({ id: 'surprise-bag-story', title: 'A very good surprise bag', scheduledAt: '2026-09-26T16:00:00-04:00', format: 'Story', campaign: 'Surprise Bags', status: 'idea', hook: 'Good pastry deserves a good ending.', idea: 'Show a Too Good To Go-style surprise bag being packed.', copy: 'Today’s extras, your very good surprise.', cta: 'Check today’s availability.', shotList: 'Hands packing 3–4 items; closed bag.', instructions: 'No faces; film at end of service.' }),
  item({ id: 'tiny-team', title: 'Running a bakery as a tiny team', scheduledAt: '2026-09-29T10:00:00-04:00', format: 'Reel', campaign: 'The Edelweiss Story', status: 'idea', hook: 'A tiny team can still make a thousand careful things.', idea: 'Warm animated pilot teaser introducing Alex and Valentina through objects, hands and the bakery rhythm.', script: 'Some bakeries begin with a business plan. Ours began with chocolate in a home kitchen, two pairs of hands, and a very early alarm.', copy: 'The Edelweiss Story is coming: small moments from nineteen years behind one tiny bakery.', cta: 'Follow for the first chapter.', shotList: 'Reference stills: home-kitchen chocolate, keys, apron, oven, storefront.', instructions: 'Select 6 archive photos in 10 minutes; no filming needed.' }),
  item({ id: 'story-pilot', title: 'The Edelweiss Story — pilot: The 2 AM shift', scheduledAt: '2026-10-13T10:00:00-04:00', format: 'Reel', campaign: 'The Edelweiss Story', status: 'idea', priority: 'alta', hook: 'At 2 AM, Biddeford is quiet. The bakery is not.', idea: '30–45 second warm handcrafted animation pilot; potential biweekly series.', script: 'At 2 AM the town is quiet. Alex turns on the light. Dough waits for no one, but it rewards patience. By the time Biddeford wakes, the first trays are ready.', copy: 'Chapter one: The 2 AM shift. A small story about the hours hidden inside your morning pastry.', cta: 'Follow the story, every other week.', shotList: 'Clock, keys, light switch, dough, oven glow, empty Main Street, finished tray.', instructions: 'Archive/reference selection only. Future episodes: home kitchen to Biddeford; Switzerland, Nicaragua and Maine; chocolate trouble; nineteen years; January 2024 opening; three-day croissant; tiny team.' }),
];
