import type { Campaign, ContentItem } from "./content-types";

const blankMetrics = { reach: 0, views: 0, retention: 0, saves: 0, shares: 0, comments: 0, clicks: 0, attributedSales: 0 };

export const campaigns: Campaign[] = [
  {
    id: "campaign-giveaway-5000",
    name: "5K Followers Giveaway",
    status: "Confirmed",
    objective: "Celebrate the community milestone and increase meaningful engagement.",
    description: "Prize: a box of six autumn chocolates. Entry: follow @edelweissmaine, like, tag someone and comment which flavor feels like autumn.",
    notes: "Confirmed close: Sep 8 at 11:59 PM ET. Winner announcement: Sep 10. Prize pickup at Edelweiss after the announcement.",
  },
  {
    id: "campaign-edelweiss-story",
    name: "The Edelweiss Story",
    status: "Future / pilot planning",
    objective: "Humanize the brand through a warm, lightly animated narrative series.",
    description: "30–45 second illustrated pilot, then biweekly if it performs. Voice-over, subtitles and restrained motion; previous emails are the narrative source.",
    notes: "Potential episodes: The 2 AM shift; From a home kitchen to Biddeford; Switzerland, Nicaragua and Maine; When chocolate refuses to cooperate; Nineteen years behind one small bakery; Opening day in January 2024; What three days inside a croissant really means; Running a bakery as a tiny team.",
  },
];

export const initialContent: ContentItem[] = [
  {
    id: "giveaway-launch", title: "5K followers — autumn chocolate giveaway", scheduledAt: "2026-08-28T10:00:00-04:00", platform: "Instagram", format: "Carousel", category: "Giveaway", campaign: "5K Followers Giveaway", objective: "Community celebration and engagement", owner: "Aitor", status: "Approved", priority: "High", materialSource: "Aitor prepares", hook: "5,000 of you are here — so we made something sweet to celebrate.", creativeIdea: "Five-image carousel treating the autumn chocolates like jewelry.", script: "", finalCopy: "5,000 of you. One very sweet thank-you. 🍂 We’re giving away a box of six handcrafted autumn chocolates. To enter: follow @edelweissmaine, like this post, tag someone you’d share it with, and tell us which flavor reminds you of fall. Entries close September 8 at 11:59 PM ET. The winner will be announced September 10.", cta: "Enter in the comments.", shotList: "Existing five-image carousel", instructions: "No action needed from Edelweiss. Aitor has prepared the assets and publishing plan.", assetLinks: ["C:\\STUDIOS-MEDIA\\social\\clientes\\edelweiss\\deliverables\\2026-08-28-giveaway-5000"], driveUrl: "", internalNotes: "Dates confirmed by Aitor: closes Sep 8 at 11:59 PM ET; winner announced Sep 10.", publishedAt: "", deadline: "2026-08-28", duration: "", orientation: "Square carousel", visualReference: "", delivered: true, metrics: blankMetrics,
  },
  {
    id: "giveaway-last-call", title: "Giveaway — last call", scheduledAt: "2026-09-08T17:00:00-04:00", platform: "Instagram", format: "Story", category: "Giveaway", campaign: "5K Followers Giveaway", objective: "Capture final qualified entries", owner: "Aitor", status: "Approved", priority: "High", materialSource: "Aitor prepares", hook: "Last chance to enter 🍂", creativeIdea: "Reuse the prepared Story creative and add a clear closing time.", script: "", finalCopy: "Last chance to enter our 5K autumn chocolate giveaway. Entries close tonight at 11:59 PM ET.", cta: "View the giveaway post", shotList: "Reuse prepared Story", instructions: "No action required.", assetLinks: ["C:\\STUDIOS-MEDIA\\social\\clientes\\edelweiss\\deliverables\\2026-08-28-giveaway-5000"], driveUrl: "", internalNotes: "Confirmed closing date.", publishedAt: "", deadline: "2026-09-08", duration: "5 sec", orientation: "Vertical 9:16", visualReference: "", delivered: true, metrics: blankMetrics,
  },
  {
    id: "giveaway-winner", title: "Giveaway winner announcement", scheduledAt: "2026-09-10T10:00:00-04:00", platform: "Instagram", format: "Story", category: "Giveaway", campaign: "5K Followers Giveaway", objective: "Announce the winner transparently and thank participants", owner: "Aitor", status: "Idea", priority: "High", materialSource: "Aitor prepares", hook: "We have a winner 🍂", creativeIdea: "Simple branded Story; verify eligibility before adding the winner's handle.", script: "", finalCopy: "We have a winner! Congratulations, @[verified winner]. Thank you to everyone who celebrated 5,000 followers with us.", cta: "Winner: please DM us to arrange pickup.", shotList: "Use existing chocolate imagery", instructions: "No action required until pickup is arranged.", assetLinks: [], driveUrl: "", internalNotes: "Before publishing: export eligible comments, select fairly, verify follow/like/tag/comment requirements, document the selection, then contact the winner. Never request payment or card details.", publishedAt: "", deadline: "2026-09-10", duration: "5–8 sec", orientation: "Vertical 9:16", visualReference: "", delivered: true, metrics: blankMetrics,
  },
  {
    id: "giveaway-story-1", title: "Giveaway launch reminder", scheduledAt: "2026-08-28T15:00:00-04:00", platform: "Instagram", format: "Story", category: "Giveaway", campaign: "5K Followers Giveaway", objective: "Drive entries to the feed post", owner: "Aitor", status: "Approved", priority: "High", materialSource: "Aitor prepares", hook: "A little thank-you for 5,000 followers", creativeIdea: "Use the prepared Story creative with a direct link to the post.", script: "", finalCopy: "We made a little autumn thank-you. Tap to enter.", cta: "View post", shotList: "Existing Story creative", instructions: "No recording required.", assetLinks: ["C:\\STUDIOS-MEDIA\\social\\clientes\\edelweiss\\deliverables\\2026-08-28-giveaway-5000"], driveUrl: "", internalNotes: "One of three existing Stories.", publishedAt: "", deadline: "2026-08-28", duration: "5 sec", orientation: "Vertical 9:16", visualReference: "", delivered: true, metrics: blankMetrics,
  },
  {
    id: "croissant-hands", title: "Three days inside a croissant", scheduledAt: "2026-09-02T10:00:00-04:00", platform: "Instagram", format: "Reel", category: "Education", campaign: "Always-on content", objective: "Show craftsmanship without requiring on-camera speaking", owner: "Shared", status: "Pending recording", priority: "Medium", materialSource: "Alex & Valentina record", hook: "A croissant doesn’t take three days because we’re slow.", creativeIdea: "Macro shots of hands, folds, butter layers, oven and final break-open.", script: "Day one: dough. Day two: layers. Day three: patience pays off.", finalCopy: "Three days. Countless layers. One very good reason to get up early. Our croissants are laminated slowly, baked fresh and best enjoyed while the layers still whisper.", cta: "Save this for your next Biddeford morning.", shotList: "Hands folding dough\nButter layer close-up\nRolling pin\nTray entering oven\nCroissant break-open", instructions: "Film five short clips, 3–4 seconds each. Only hands and product; no talking and no faces needed. Hold the phone steady and leave a second before and after each action.", assetLinks: [], driveUrl: "", internalNotes: "One recording should also supply two Stories and a still post.", publishedAt: "", deadline: "2026-08-31", duration: "20 minutes total recording", orientation: "Vertical 9:16", visualReference: "Close, warm, tactile; natural bakery sound.", delivered: false, metrics: blankMetrics,
  },
  {
    id: "story-oven", title: "Morning oven moment", scheduledAt: "2026-09-04T08:30:00-04:00", platform: "Instagram", format: "Story", category: "Behind the scenes", campaign: "Always-on content", objective: "Maintain a sustainable weekly presence", owner: "Aitor", status: "Idea", priority: "Low", materialSource: "Reuse existing material", hook: "Good morning from the warmest corner of Biddeford.", creativeIdea: "Reuse oven footage from the croissant session with one line of copy.", script: "", finalCopy: "Good morning from the warmest corner of Biddeford.", cta: "Visit us today", shotList: "Reuse oven clip", instructions: "No additional action required.", assetLinks: [], driveUrl: "", internalNotes: "Designed to reuse the same biweekly recording session.", publishedAt: "", deadline: "", duration: "5 sec", orientation: "Vertical 9:16", visualReference: "", delivered: true, metrics: blankMetrics,
  },
  {
    id: "animated-pilot", title: "Pilot — The 2 AM shift", scheduledAt: "2026-10-09T10:00:00-04:00", platform: "Instagram", format: "Reel", category: "Alex & Valentina", campaign: "The Edelweiss Story", objective: "Test the animated brand-story format", owner: "Aitor", status: "Idea", priority: "Medium", materialSource: "No Edelweiss action", hook: "At 2 AM, the bakery has its own weather system.", creativeIdea: "Handcrafted illustration, gentle parallax, tiny flour-cloud gag and warm voice-over.", script: "Draft from the strongest anecdote in previous email stories.", finalCopy: "", cta: "Follow for the next chapter.", shotList: "No new filming required; use existing portraits and bakery references.", instructions: "No action required unless Aitor asks for one story check before production.", assetLinks: [], driveUrl: "", internalNotes: "30–45 seconds. Higgsfield for frames/clips; Remotion for edit, titles and subtitles.", publishedAt: "", deadline: "2026-09-25", duration: "30–45 sec", orientation: "Vertical 9:16", visualReference: "Artisanal illustrated warmth; not feature-film animation.", delivered: true, metrics: blankMetrics,
  },
];
