"use client";
import { useState } from 'react';
import { BarChart3, CalendarDays, Mail, RefreshCw, ShoppingBag, Sparkles } from 'lucide-react';
import { MetaAdsDashboard } from './MetaAdsDashboard'; import { EmailDashboard } from './EmailDashboard'; import { ContentCalendar } from './ContentCalendar';
import type { MetaAdData, EmailCampaignData, EmailSubscriberData } from '@/lib/data'; import type { ContentItem } from '@/lib/content-types';
import type { OrdersAndRequestsData } from '@/lib/data'; import { OrdersDashboard } from './OrdersDashboard';
export function DashboardTabs({ metaData, emailData, subscriberData, ordersData, contentItems, persistence }: { metaData: MetaAdData[]; emailData: EmailCampaignData[]; subscriberData: EmailSubscriberData[]; ordersData: OrdersAndRequestsData; contentItems: ContentItem[]; persistence: 'redis' | 'seed' }) {
 const [active,setActive]=useState<'content'|'orders'|'meta'|'email'>('content'); const [syncing,setSyncing]=useState(false); const [sync,setSync]=useState<{completedAt?:string;brevo?:{source:string};meta?:{source:string}}>({});
 async function syncNow(){setSyncing(true);try{const r=await fetch('/api/sync',{method:'POST'});setSync(await r.json());}finally{setSyncing(false)}}
  return <div className="app-shell"><aside className="sidebar"><div className="brand-mark">E</div><div className="brand-copy"><strong>Edelweiss</strong><span>Marketing Studio</span></div><nav>{[{id:'content',label:'Content Calendar',icon:CalendarDays},{id:'orders',label:'Orders & requests',icon:ShoppingBag},{id:'meta',label:'Meta Ads',icon:BarChart3},{id:'email',label:'Email Marketing',icon:Mail}].map(x=><button key={x.id} className={active===x.id?'active':''} onClick={()=>setActive(x.id as typeof active)}><x.icon size={18}/><span>{x.label}</span></button>)}</nav><div className="sidebar-note"><Sparkles size={17}/><div><strong>The Edelweiss Story</strong><span>Pilot · October</span></div></div></aside><main className="workspace"><header className="topbar"><div><span className="mobile-brand">Edelweiss</span><span className="season">September 2026 · Biddeford, Maine</span></div><div className="sync-control"><div>{sync.completedAt?<><strong>Synced</strong><span>{new Date(sync.completedAt).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})} · Brevo {sync.brevo?.source} · Meta {sync.meta?.source}</span></>:<><strong>Performance data</strong><span>API pending · Sheets active as fallback</span></>}</div><button onClick={syncNow} disabled={syncing}><RefreshCw size={16} className={syncing?'spin':''}/>{syncing?'Syncing':'Sync now'}</button></div></header><div className="mobile-nav">{[['content','Plan'],['orders','Orders'],['meta','Meta'],['email','Email']].map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id as typeof active)}>{label}</button>)}</div><div className="workspace-body">{active==='content'&&<ContentCalendar initialItems={contentItems} persistence={persistence}/>} {active==='orders'&&<OrdersDashboard data={ordersData}/>} {active==='meta'&&<div className="performance-wrap"><div className="section-heading"><div><span className="eyebrow">Performance</span><h2>Meta Ads</h2></div></div><MetaAdsDashboard data={metaData}/></div>} {active==='email'&&<div className="performance-wrap"><div className="section-heading"><div><span className="eyebrow">Performance</span><h2>Email Marketing</h2></div></div><EmailDashboard campaignData={emailData} subscriberData={subscriberData}/></div>}</div></main></div>;
}
