"use client";
import { Camera, ExternalLink, Eye, Heart, MousePointerClick, Sparkles, TrendingUp, Users } from "lucide-react";
import type { InstagramAnalytics } from "@/lib/content-types";

const compact = (value: number | null) => value === null ? "—" : new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(value);

export function InstagramDashboard({ data }: { data: InstagramAnalytics }) {
  if (!data.configured) return <div><Header/><div className="notice mt-6"><Camera size={20}/><div><strong>Authorization pending — the module is ready</strong><p>Complete the official Meta app and add the server-only token to begin collecting real Instagram history. No password or scraping is required.</p></div></div><EmptyArchitecture/></div>;
  return <div><Header/><p className="mt-2 text-sm text-[var(--muted)]">Last sync: {data.lastSyncedAt ? new Date(data.lastSyncedAt).toLocaleString() : "Never"}</p><div className="mt-7 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Followers" value={compact(data.account.followers)} detail={data.followerChange === null ? "Baseline pending" : `${data.followerChange >= 0 ? "+" : ""}${data.followerChange} since prior snapshot`} icon={<Users/>}/><Metric label="Reach" value={compact(data.account.reach)} detail="Latest available account period" icon={<Eye/>}/><Metric label="Profile views" value={compact(data.account.profileViews)} detail="Reported by Meta" icon={<TrendingUp/>}/><Metric label="Website clicks" value={compact(data.account.websiteClicks)} detail="When available" icon={<MousePointerClick/>}/></div><section className="mt-8"><p className="eyebrow">Evidence, not guesses</p><h2 className="font-serif text-3xl">Recommended next moves</h2>{data.recommendations.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{data.recommendations.map((item) => <article className="card p-5" key={item.title}><span className="status-pill">{item.confidence}</span><h3 className="mt-3 font-serif text-xl">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-[var(--muted)]">{item.detail}</p></article>)}</div> : <div className="empty-state mt-4"><Sparkles/><h3>Collecting a trustworthy sample</h3><p>Recommendations appear after at least four measured publications. Reliable labels require ten or more.</p></div>}</section><section className="mt-8"><p className="eyebrow">Content performance</p><h2 className="font-serif text-3xl">Recent Instagram content</h2><div className="mt-4 grid gap-3">{data.media.map((item) => <article className="card grid gap-3 p-4 md:grid-cols-[1fr_auto] md:items-center" key={item.id}><div><span className="status-pill">{item.type}</span><p className="mt-2 line-clamp-2 text-sm font-semibold">{item.caption}</p><p className="mt-1 text-xs text-[var(--muted)]">{item.timestamp ? new Date(item.timestamp).toLocaleDateString() : "Date unavailable"}</p></div><div className="flex flex-wrap items-center gap-4 text-xs text-[var(--muted)]"><span><Eye className="mr-1 inline" size={14}/> {compact(item.reach)}</span><span><Heart className="mr-1 inline" size={14}/> {compact(item.likes)}</span><span>Saves {compact(item.saves)}</span><span>Shares {compact(item.shares)}</span>{item.permalink ? <a href={item.permalink} target="_blank" rel="noreferrer" className="text-[var(--forest)]" aria-label="Open Instagram publication"><ExternalLink size={16}/></a> : null}</div></article>)}{data.media.length === 0 ? <div className="empty-state"><Camera/><h3>No synchronized content yet</h3><p>Use Data sync after the token and database are configured.</p></div> : null}</div></section></div>;
}

function Header(){return <header><p className="eyebrow">Organic performance</p><h1 className="page-title">Instagram</h1><p className="mt-2 max-w-2xl text-sm text-[var(--muted)]">Live account health, content learning and low-effort recommendations for @edelweissmaine.</p></header>}
function Metric({label,value,detail,icon}:{label:string;value:string;detail:string;icon:React.ReactNode}){return <article className="card p-4 md:p-5"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">{label}</p><span className="text-[var(--forest)]">{icon}</span></div><p className="mt-4 font-serif text-3xl md:text-4xl">{value}</p><p className="mt-1 text-xs text-[var(--muted)]">{detail}</p></article>}
function EmptyArchitecture(){return <section className="mt-8 grid gap-4 md:grid-cols-3"><article className="card p-5"><span className="status-pill">1 · Connect</span><h2 className="mt-3 font-serif text-xl">Official Meta API</h2><p className="mt-2 text-sm text-[var(--muted)]">Read-only token, server-only storage and isolated permissions.</p></article><article className="card p-5"><span className="status-pill">2 · Learn</span><h2 className="mt-3 font-serif text-xl">Daily history</h2><p className="mt-2 text-sm text-[var(--muted)]">Followers, account Insights and performance per publication.</p></article><article className="card p-5"><span className="status-pill">3 · Improve</span><h2 className="mt-3 font-serif text-xl">Measured recommendations</h2><p className="mt-2 text-sm text-[var(--muted)]">Signals are labelled early or reliable according to sample size.</p></article></section>}


